config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:new, :create]
  resource :session, only:[:new, :create, :destroy]
  resources :walls, only:[:index, :create, :new, :show, :edit, :update]
  resources :wall_rental_requests, only:[:new, :create] do
    member do
        post :approve
        post :deny
    end 
  end 
  
end

app/models/wall.rb
class Wall < ApplicationRecord
    include ActionView::Helpers::DateHelper

    validates :construction_date, presence: true
    validates :name, presence: true, uniqueness: true
    validates :wall_material, inclusion: { in: %w(brick concrete wood cement clay),
        message: "isn't valid" }
    validates :size, inclusion: { in: %w(small medium large),
        message: "%(value) isn't valid" }
    validates :owner_id, presence: true

    belongs_to(
        :owner, 
        class_name: 'User',
        primary_key: :id,
        foreign_key: :owner_id
    )
    
    def age
        time_ago_in_words(self.construction_date)
    end 

    has_many(
        :requests, dependent: :destroy,
        class_name: 'WallRentalRequest',
        foreign_key: :wall_id,
        primary_key: :id
    )
end 

app/controllers/walls_controller.rb
class WallsController < ApplicationController
    before_action :authorized_user, only: %i(update edit) 
    
    def index
        @walls = Wall.all
        render :index
    end 

    def show 
        @wall = Wall.find_by(id: params[:id])
        @usernames = @wall.requests.includes(:requester)
    
        if @wall
            render :show
        else 
            redirect_to '/walls'
        end 
    end 

    def new
        @wall = Wall.new
        render :new
    end

    def create
        @wall = current_user.walls.new(wall_params) 
        
        if @wall.save!
            redirect_sto wall_url(@wall)
        else 
            flash.now[:errors] = @wall.errors.full_messages
            render :new
        end 
    end 

    def edit
        @wall = current_user.walls.find_by(id: params[:id])
        render :edit
    end 
    
    def update
        @wall = current_user.walls.find_by(id: params[:id])

        if @wall.update_attributes(wall_params)
            redirect_to wall_url(@wall)
        else 
            flash.now[:errors] = @wall.errors.full_messages
            render :edit
        end
    end  
    
    private

    def wall_params
        params.require(:wall).permit(:name, :coat_color, :construction_date, :wall_material, :description, :size, :owner_id)
    end

end 

app/views/walls/_form.html.erb
<head>
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;700&display=swap" rel="stylesheet">
</head>

<% if wall.persisted? %>
    <% action_url = wall_url(wall) %>
<% else %>
    <% action_url = walls_url %>
<% end %>

<% method = (wall.persisted? ? :patch : :post) %>


<form action="<%= action_url %>" method="post">
    <input type="hidden" name="_method" value="<%= method %>">
    <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
   
    <label for="name">Name</label>
    <input id="name" type="text" name="wall[name]" value="<%= wall.name %>">

<br><br>

<label for="wall_material">Choose a Wall Material:</label>

<select for="wall_material" name="wall[wall_material]">
    <option value="brick" <%= wall.wall_material == "brick" ? "selected" : ""%> >brick</option>
    <option value="concrete" <%= wall.wall_material == "concrete" ? "selected" : ""%> >concrete</option>
    <option value="wood" <%= wall.wall_material == "wood" ? "selected" : ""%> >wood</option>
    <option value="cement" <%= wall.wall_material == "cement" ? "selected" : ""%> >cement</option>
    <option value="clay" <%= wall.wall_material ? "selected" : ""%> >clay</option>
</select>

<br><br>

    <label for="size">Size:</label>
    <input type="radio" id="size" name="wall[size]" value="small" <%= wall.size == "small" ? "checked" : ""%> >
    <label for="small">Small</label>
    
    <input type="radio" id="size" name="wall[size]" value="medium" <%= wall.size == "medium" ? "checked" : ""%> >
    <label for="medium">Medium</label>

    <input type="radio" id="size" name="wall[size]" value="large" <%= wall.size == "large" ? "checked" : ""%> >
    <label for="large">Large</label>

<br><br>

<label for="wall_construction_date">Construction Date</label>

<input 
    type="date" 
    id="wall_construction_date" 
    name="wall[construction_date]"
    value="<%= wall.construction_date %>">

<br><br>

<label for="description">Description:</label>

<textarea id="description" name="wall[description]"
    row="5" col="33"><%= 
        wall.description%>
</textarea>

<br><br>

 <% submit_text = (wall.persisted? ? 'Update' : 'Create') + ' wall!' %>
  <input type="submit" value="<%= submit_text %>">
</form> 







    

app/views/walls/edit.html.erb
<h1>Edit Wall in Collection:</h1>

<%= render 'form', wall: @wall%>


<!-- <form action="<%= wall_url(@wall) %>" method="post">
   <input type="hidden" name="_method" value="PATCH">
   
    <label for="name">Name</label>
    <input id="name" type="text" name="wall[name]" value="<%= @wall.name %>">

<br><br>

<label for="wall_material">Choose a Wall Material:</label>

<select for="wall_material">
    <option value="brick" <%= @wall.wall_material == "brick" ? "selected" : ""%> >brick</option>
    <option value="concrete" <%= @wall.wall_material == "concrete" ? "selected" : ""%> >concrete</option>
    <option value="wood" <%= @wall.wall_material == "wood" ? "selected" : ""%> >wood</option>
    <option value="cement" <%= @wall.wall_material == "cement" ? "selected" : ""%> >cement</option>
    <option value="clay" <%= @wall.wall_material == "clay" ? "selected" : ""%> >clay</option>
</select>

<br><br>

    <label for="size">Size:</label>
    <input type="radio" name="size" value="small" <%= @wall.size == "small" ? "checked" : ""%> >
    <label for="small">Small</label>
    
    <input type="radio" name="size" value="medium" <%= @wall.size == "medium" ? "checked" : ""%> >
    <label for="medium">Medium</label>

    <input type="radio" name="size" value="large" <%= @wall.size == "large" ? "checked" : ""%> >
    <label for="large">Large</label>

<br><br>

<label for="construction">Construction Date:</label>

<input type="text" id="construction" name="wall[construction_date]"
       value=" <%= @wall.construction_date %>">

<br><br>

<label for="description">Description:</label>

<textarea id="description" name="wall[description]"
    row="5" col="33"><%= 
        @wall.description %>
</textarea>

<br><br>

<input type="submit" value="Send Request">
</form> -->







    

app/views/walls/index.html.erb
<h1>Welcome to the Wall Rental Space</h1>

<section class="purpose"> 
    <h3>Purpose of this site</h3>
        <p>
        This is a test site built by Neka Kerr to demonstrate her coding abilities. It was built in Ruby on Rails, HTML, CSS, & PostgreSQL and is intended
        for street artists to schedule time for their curated mural to be displayed on a given wall.
        </p>

        <p>
        To see the full funtionality of the site, log in as the Verdun Street wall owner 'neka'
        using the password 'password'. This will allow you to approve and deny rental requests
        for the Verdun Street wall. 
        </p>
</section>

<section class="ordered-list">
    <h3 class="specific">Available Walls</h3>

        <ol>
            <% @walls.each do |wall| %>
                <li>
                <a href="<%= wall_url(wall) %>">              
                <%= wall.name %>
                </a>
                </li>
            <% end %>
        </ol> 

app/views/walls/new.html.erb
<h1>Add Wall to Collection</h1>

<%= render 'form', wall: @wall%>


<!-- <form action="/walls" method="post">
    <label for="name">Name</label>
    <input for="name" type="text" name="wall[name]">


<br><br>

<label for="wall_material">Wall Material:</label>

<select name="wall[wall_material]">
    <option disabled selected>--Please Choose an Option--</option>
    <option value="brick">brick</option>
    <option value="concrete">concrete</option>
    <option value="wood">wood</option>
    <option value="cement">cement</option>
    <option value="clay">clay</option>
</select> 

<br><br>

    <label for="size">Size:</label>
    <input type="radio" name="wall[size]" value="small">
    <label for="small">Small</label>
    
    <input type="radio" name="wall[size]" value="medium">
    <label for="medium">Medium</label>

    <input type="radio" name="wall[size]" value="large">
    <label for="large">Large</label>

<br><br>

<label for="construction">Construction Date:</label>

<input type="date" id="construction" name="wall[construction_date]"
       value="2020-08-26"
       min="2000-01-01" max="2020-08-26">

<br><br>

<label for="description">Description:</label>

<textarea id="description" name="wall[description]"
    row="5" col="33">

</textarea>

<br><br>

<input type="submit" value="Send Request">
</form> -->

    

app/views/walls/show.html.erb
<head>
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;700&display=swap" rel="stylesheet">
</head>

<h1><%= @wall.name %></h1>

<section class="img-details">
    <figure>
        <img class="fit-picture" 
            src="<%= image_url('https://www.rosekennedygreenway.org/wp-content/uploads/2019/08/RKG_2019_ART_Thelan_01-1024x683.jpg" alt="Resonance') %>">
            
            <figcaption class="figcaption">
            <a href="https://www.rosekennedygreenway.org/wp-content/uploads/2019/08/RKG_2019_ART_Thelan_01-1024x683.jpg">Resonance, 2019 by: Super A (Stefan Thelen)</a>
            </figcaption>
        </figure>
<p>        
<table>
    <thead>
        <tr>
            <th colspan="3">Wall Details</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><b>Wall Material:</b> <%= @wall.wall_material %></td>
            <td><b>Size:</b> <%= @wall.size %></td>
            <td><b>Construction Date:</b> <%= @wall.construction_date %></td>
        </tr>
    </tbody>
</table>

<b>Description:</b>
<%= @wall.description %>
<br><br>

<% if @wall.owner == current_user %>
    <a href="<%= edit_wall_url(@wall) %>">Edit <%= @wall.name %></a>
<% end %>

</p>
</section >

<p>   

<% is_wall_owner = current_user && current_user.owns_wall?(@wall) %>


<section class="reservations">

<h4>Current Reservations on <%= @wall.name %></h4>
<% if @usernames.empty? %>
    <p> <%= @wall.name %> has no rental requests currently.</p>
<% else %> 
<ol>
<% @usernames.order('start_date').each do |rental_request| %>
    <li> Username: <%= rental_request.requester.username %>
    <br>
    Status: <%= rental_request.status %></li>
    Start Date: <%= rental_request.start_date  %>
    <br>
    End Date: <%= rental_request.end_date %> 
        <% if rental_request.status == "PENDING" && is_wall_owner %>
            <br>
            wall_id: <%= rental_request.wall_id %>
            id: <%= rental_request.id %>
            <form action=" <%= approve_wall_rental_request_url(rental_request.id) %>" method="post" class="wall_rental_request[status]">
                <input class="wall_rental_request[status]"
                 type="submit" value="APPROVE">
            </form>

            <form action=" <%= deny_wall_rental_request_url(rental_request.id) %>" method="post" class="wall_rental_request[status]">
                <input class="wall_rental_request[status]"
                 type="submit" value="DENY">
            </form> 
        <% end %>
    <% end %>
    </ol>
<% end %>
</p>

<p>
<% if !current_user.nil? %>
    <a href="<%= new_wall_rental_request_url(wall_id: @wall.id) %>">Make new request</a>
  <% end %>
</p>

</section>