config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:new, :create]
  resource :session, only:[:new, :create, :destroy]
  resources :walls, only:[:index, :create, :new, :show, :edit, :update]
  resources :wall_rental_requests, only:[:new, :create] do
    member do
        post :approve
        post :deny
    end 
  end 
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wall Rental Site</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;700&display=swap" rel="stylesheet">
  </head>


  <body>
  <header>
    <ul>
    <nav>
    <li><a href="<%= walls_url %>">Home
      </a></li>

    <% if current_user.nil? %>
        <li> <a href="<%= new_user_url %>">Sign Up</a></li>
        <li><a href="<%= new_session_url %>">Sign In</a></li>
    <% else %>
      <li><%= current_user.username %> is logged in.
      <form action="<%= session_url %>" method="post">
        <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="Logout">
      </form></li>    
    <% end %>  
    </ul>
    </nav>
  </header>



    <%= yield %>
  </body>
</html>